marco-prontera/vite-plugin-css-injected-by-js

- package-lock.json
- package.json
The goal of this PR is to update the package to npm.
Issue code [#6]
> [#6] Create release 1.0.1

- package-lock.json
- package.json
- src/plugin.ts
- tsconfig.json
> [#12] Fix lib for Vite Plugin Legacy

- package-lock.json
- package.json
- src/index.ts
Closes #14 
Available preview at https://www.npmjs.com/package/vite-plugin-css-injected-by-js/v/1.3.0-beta
> [#14] Fix export default

- package-lock.json
> [#23] Update package lock

- README.md
- package-lock.json
- package.json
- src/index.ts
The goal of this PR:
- Prepare the project for new release
- Add `styleId` optional param
closes #27
> [#27] Add StyleId param

- package-lock.json
- package.json
- src/index.ts
> [#18] CSS Link Is still generated

- .prettierrc
- cjs-esm-fixup
- package-lock.json
- package.json
- src/index.ts
- src/utils.ts
- tsconfig-base.json
- tsconfig-cjs.json
- tsconfig.json
> [#30] ESM & CJS support and bugfixing

- package-lock.json
- package.json
- src/index.ts
> [#33] Fix utils import for ESM usage with '.js' suffix

- package-lock.json
- package.json
- src/index.ts
> [#35] Build CSS code outside html cleaning block

- src/utils.ts
> [#40] Fix styleId to be a string instead of a variable

- .prettierrc
- package-lock.json
- package.json
- src/index.ts
- src/utils.ts
> [#41] Improve Typescript types for Plugin's parameters

- src/utils.ts
> [#44] Check if document object exists before using it

- package-lock.json
- package.json
> [#49] Fix Typescript types

- README.md
- package-lock.json
- package.json
- src/index.ts
- src/utils.ts
> [#56] Release 2.2.0

- package-lock.json
- package.json
- src/index.ts
- src/utils.spec.ts
- src/utils.ts
- vitest.config.ts
Refactored injection code to support writing literal JS / TS instead of requiring string building.
Added tests to ensure base case continues to work
> ✨ Refactor, add tests 💚

- .github/workflows/ci.yml
- README.md
- package-lock.json
- package.json
- src/index.ts
- src/interface.ts
- src/utils.ts
- test/utils.spec.ts
> [#58] Injected code goes in the wrong chunk

- package-lock.json
- package.json
- src/interface.ts
> [#67] Fix type def

- .github/workflows/ci.yml
- .gitignore
- package-lock.json
- package.json
- src/utils.ts
- test/utils.spec.ts
- vitest.config.ts
> [#72] Introduce Istanbul for code coverage reporting

- README.md
- package-lock.json
- package.json
- src/index.ts
- src/interface.ts
- src/utils.ts
- test/utils.spec.ts
> [#76] Release 2.5.0

- .github/ISSUE_TEMPLATE/config.yml
- package-lock.json
- package.json
- src/index.ts
- src/utils.ts
- test/utils.spec.ts
> [#84] Fix bugs relativeCSSInjection (experimental feature) and empty injection

- README.md
- package-lock.json
- package.json
- src/index.ts
- src/interface.ts
The goal of this PR is to implement an option to exclude some css files to be injected.
closes #54
> [#54] Option to exclude some css files to be injected

- package-lock.json
- package.json
- src/interface.ts
- src/utils.ts
> Delete viteMetadata declaration since isn't required

- package-lock.json
- package.json
- src/utils.ts
> [#103] Improve support for more chunk filename formats

- README.md
- package-lock.json
- package.json
- src/utils.ts
> [#108] Fix injection for multiple build of same entry point

- .github/workflows/ci.yml
- LICENSE
- README.md
- SECURITY.md
- package-lock.json
- package.json
> [#119] Update repository

- package-lock.json
- package.json
> [#125] feat: support cross platform for unix shell command 'rm -rf'

- README.md
- package-lock.json
- package.json
- src/index.ts
- src/interface.ts
- src/utils.ts
> [#137] Add format param for css injection code
